// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT0Cn2ptsGhXR-L2Mvk5aQs-xKLAryi-M',
    appId: '1:750754161824:web:7e2b96375408b8948755c5',
    messagingSenderId: '750754161824',
    projectId: 'chatapp-ea49f',
    authDomain: 'chatapp-ea49f.firebaseapp.com',
    storageBucket: 'chatapp-ea49f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbdu0s-F3JF-UCDW86yDmloS6M72YTvVU',
    appId: '1:750754161824:android:25f9a18820d253f18755c5',
    messagingSenderId: '750754161824',
    projectId: 'chatapp-ea49f',
    storageBucket: 'chatapp-ea49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1P41Mw3SL8bbWHLKPpnW6vRt1BLEqhkQ',
    appId: '1:750754161824:ios:25086d236b49911f8755c5',
    messagingSenderId: '750754161824',
    projectId: 'chatapp-ea49f',
    storageBucket: 'chatapp-ea49f.appspot.com',
    iosClientId: '750754161824-qujkjinat4m4seb5877n0oi44ks43deo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1P41Mw3SL8bbWHLKPpnW6vRt1BLEqhkQ',
    appId: '1:750754161824:ios:a371a32d9bae9d118755c5',
    messagingSenderId: '750754161824',
    projectId: 'chatapp-ea49f',
    storageBucket: 'chatapp-ea49f.appspot.com',
    iosClientId: '750754161824-5d9s6ti27ctmcv5dnjghqgjk0hplvgbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
